name: GitHub Actions
on: [push, pull_request]
jobs:
  github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Info
        run: echo "ğŸ‰ triggered on ${{ github.event_name }} event"
          echo "ğŸ§ running on a ${{ runner.os }} server hosted by GitHub"
          echo "ğŸ” ${{ github.ref_name }} branch from ${{ github.repository }} is being used."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: List files in the repository
        run: echo "ğŸ’¡ The repo has been cloned to the runner."
          echo "ğŸ–¥ï¸ ready to test your code on the runner."
          ls ${{ github.workspace }}
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2
      - name: install the repo
        run: pnpm install
          echo "ğŸ‰ pnpm installed the repo"
      - name: run tests
        run: pnpm run lint
      - name: fin
        run: echo "ğŸ ${{ job.status }}."
