name: GitHub Actions Demo
on: [push, pull_request]
jobs:
  GitHub-Actions:
    runs-on: windows-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The ${{ github.ref }} branch of ${{ github.repository }} is being used."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The repo has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Setup node
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2
      - run: pnpm install
      - run: echo "ğŸ‰ pnpm installed the repo"
      - run: pnpm run lint
      - run: echo "ğŸ This job's status is ${{ job.status }}."
