name: GitHub Actions Demo
on: [push, pull_request]
jobs:
  GitHub-Actions:
    runs-on: windows-latest
    steps:
      - name: Info
        run: 
          echo "ğŸ‰ triggered on ${{ github.event_name }} event" &&
          echo "ğŸ§ running on a ${{ runner.os }} server hosted by GitHub" &&
          echo "ğŸ” ${{ github.ref_name }} branch from ${{ github.repository }} is being used."
      - name: Check out repository code
        uses: actions/checkout@v2
        run:
          echo "ğŸ’¡ The repo has been cloned to the runner." &&
          echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Setup node and pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2
        run: 
          pnpm install &&
          echo "ğŸ‰ pnpm installed the repo"
      # - name: Testing
      #   run: pnpm run lint
      - name: CI / CD
      - if: ${{ job.status == 'cancelled'}}
        run: echo "ğŸ The workflow was ${{ job.status }}."
      - if: ${{ job.status != 'cancelled'}}
        run: echo "ğŸ The workflow was a ${{ job.status }}."
